"""Change alert_cadence column in users table to string

Revision ID: 21f2a039b12b
Revises: a9e816e93d08
Create Date: 2022-01-05 00:47:09.862881

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '21f2a039b12b'
down_revision = 'a9e816e93d08'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'alert_cadence',
               existing_type=postgresql.ARRAY(sa.INTEGER()),
               type_=sa.String(),
               existing_nullable=True,
               schema='cloud_monitor')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'alert_cadence',
               existing_type=sa.String(),
               type_=postgresql.ARRAY(sa.INTEGER()),
               existing_nullable=True,
               schema='cloud_monitor')
    # ### end Alembic commands ###
