"""Create table metrics

Revision ID: 878a06d81391
Revises: 1f93f5096588
Create Date: 2021-12-29 15:49:35.648922

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '878a06d81391'
down_revision = '1f93f5096588'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('metrics',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('dimension', sa.String(), nullable=False),
    sa.Column('region', sa.String(), nullable=True),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.Column('response_time', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='cloud_monitor'
    )
    op.create_index('idx_metrics_created', 'metrics', [sa.text('timestamp DESC')], unique=False, schema='cloud_monitor')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_metrics_created', table_name='metrics', schema='cloud_monitor')
    op.drop_table('metrics', schema='cloud_monitor')
    # ### end Alembic commands ###
