"""Add users table

Revision ID: a9e816e93d08
Revises: 878a06d81391
Create Date: 2022-01-04 00:21:05.383214

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a9e816e93d08'
down_revision = '878a06d81391'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', postgresql.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_upd', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('signup_for', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('service_alerts', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('alert_cadence', sa.ARRAY(sa.Integer()), nullable=True),
    sa.Column('email', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='cloud_monitor'
    )
    op.create_index('unq_email_users', 'users', ['email'], unique=True, schema='cloud_monitor')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('unq_email_users', table_name='users', schema='cloud_monitor')
    op.drop_table('users', schema='cloud_monitor')
    # ### end Alembic commands ###
