"""Add regions to user table

Revision ID: aec7a0250afa
Revises: 21f2a039b12b
Create Date: 2022-05-04 13:09:00.541384

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aec7a0250afa'
down_revision = '21f2a039b12b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('service_regions', sa.ARRAY(sa.String()), nullable=True), schema='cloud_monitor')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'service_regions', schema='cloud_monitor')
    # ### end Alembic commands ###
